### ISSUE TITLE
The last step fails! ( git push -u origin master)

### ISSUE THREAD

**Issue by achilex** [chriswirz/openshift-redmine-3.0.1-quickstart#1]
Hi chriswirz,

I follow the steps you indicated the installation was successful(ruby 1.9, rails 4.2.0), but there is a question to ask?
The last step ( git push -u origin master) "Failed to add the host to the list of known hosts" error message will appear.
How can I solve this problem?

Thx!

**Comment by chriswirz** [comment]
Good catch!  I forgot to mention that you need to add your ssh keys.  Here is the new description:

Once the gear is functioning properly, add the contents to the the repository. You must have the gear's ssh key added to your remote repository's (or application's) allowed key collection. This example just shows you how to push to your gear's repo, but I have also tested this with github (the repo you're looking at now).

**Comment by chriswirz** [comment]
Also, you don't really need to push to repo...  The gear should be running and upgrading redmine can be done through another wget.  The instructions are really specific for openshift.

**Comment by chriswirz** [comment]
Also, I couldn't get it to work with rails...  There was only one combination (I tried several) that I got to work.

The Openshift application must be configured as follows:
Ruby 1.9 or 2.0 (no scaling)
MySql 5.1
