### ISSUE TITLE
permission issue 

### ISSUE THREAD

**Issue by gajjar8055** [chriswirz/openshift-redmine-3.0.1-quickstart#2]
gem install bundler -no-ri -no-rdoc
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/openshift/568f67f60c1e6631c0000001/app-root/o-rdoc

**Comment by jmoraxoftix** [comment]
Please use:
- sudo gem install bundler -no-ri -no-rdoc
